dist: trusty
sudo: required
services:
  - docker
language: python
python:
  - "2.4"
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
matrix:
  include:
    - env: TARGET=sanity
    - env: TARGET=sanity
      python: 2.4
    - env: TARGET=sanity
      python: 2.6
    - env: TARGET=sanity
      python: 2.7
    - env: TARGET=sanity
      python: 3.4
    - env: TARGET=sanity
      python: 3.5
    - env: TARGET=centos6
    - env: TARGET=centos7 TARGET_OPTIONS="--volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - env: TARGET=fedora23 TARGET_OPTIONS="--volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - env: TARGET=fedora-rawhide TARGET_OPTIONS="--volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - env: TARGET=ubuntu1204
    - env: TARGET=ubuntu1404
install:
  - pip install python-dbus
  - pip install python-utmp
script:
  - make test
after_success:
  - coveralls
#notifications:
#  irc:
#    channels:
#      - "chat.freenode.net#ansible-notices"
#    on_success: change
#    on_failure: always
#    skip_join: true
#    nick: ansibletravis